### PR TITLE
Add support for SAM 2

### PR DESCRIPTION
**Pull request by giswqs**
This PR adds support for Meta's Segment Anything Model 2 (SAM 2).
https://github.com/facebookresearch/segment-anything-2
https://github.com/IDEA-Research/Grounded-SAM-2?tab=readme-ov-file#grounded-sam-2-video-object-tracking-demo

Work in progress

### CODE REVIEW

**Comment by giswqs** [comment]
```python
from samgeo import SamGeo2

sam2 = SamGeo2(model_id="sam2-hiera-large", automatic=True)
image = "images/cars.jpg"
masks = sam2.generate(image)
```
image

**Comment by giswqs** [comment]
```python
from samgeo import SamGeo2

sam2 = SamGeo2(
    model_id="sam2-hiera-large",
    apply_postprocessing=False,
    points_per_side=32,
    points_per_batch=64,
    pred_iou_thresh=0.7,
    stability_score_thresh=0.92,
    stability_score_offset=0.7,
    crop_n_layers=1,
    box_nms_thresh=0.7,
    crop_n_points_downscale_factor=2,
    min_mask_region_area=25.0,
    use_m2m=True,
)
image = "images/satellite.tif"
masks = sam2.generate(image)
```

satellite

image

**Comment by giswqs** [comment]
https://github.com/user-attachments/assets/7d14b615-6afd-4673-a196-24424a6d7e16

**Comment by twoldemariam** [comment]
What an exciting time we are in!

**Comment by brendancol** [comment]
- [ ] Support SAM2 in LangSAM (https://github.com/opengeos/segment-geospatial/blob/main/samgeo/text_sam.py#L134-L150)

**Comment by giswqs** [comment]
@brendancol Yes, we should be able to add support for LangSAM.
The [Grounded SAM2](https://github.com/IDEA-Research/Grounded-SAM-2?) is also very interesting.

**Comment by giswqs** [comment]
```python
from samgeo import SamGeo2

predictor = SamGeo2(video=True)
video_path = "input_video.mp4"
predictor.set_video(video_path)
prompts = {
    1: {
        "points": [[200, 300], [275, 175]],
        "labels": [1, 0],
        "frame_idx": 0,
    },
    2: {
        "points": [[400, 150]],
        "labels": [1],
        "frame_idx": 0,
    },
}
predictor.predict_video(prompts)
predictor.save_video_segments_blended(
    "blended", output_video="output_video.mp4", fps=30
)
```

input video

https://github.com/user-attachments/assets/609443a6-fba8-4c04-9edc-d75c64b4f2f3

output video

https://github.com/user-attachments/assets/0f8f5689-5363-4c9d-bab5-e2f735136588

**Comment by giswqs** [comment]
```python
from samgeo import SamGeo2

predictor = SamGeo2(video=True)
video_path = "input_video.mp4"
predictor.set_video(video_path, frame_rate=3)
prompts = {
    1: {
        "points": [[200, 300], [275, 175]],
        "labels": [1, 0],
        "frame_idx": 0,
    },
    2: {
        "points": [[400, 150]],
        "labels": [1],
        "frame_idx": 0,
    },
}
predictor.show_prompts(prompts, frame_idx=0)
```
image

**Comment by giswqs** [comment]
```python
from samgeo import SamGeo2

predictor = SamGeo2(video=True)
video_path = "input_video.mp4"
predictor.set_video(video_path, frame_rate=3)
prompts = {
    1: {
        "points": [[200, 300], [275, 175]],
        "labels": [1, 0],
        "frame_idx": 0,
    },
    2: {
        "points": [[400, 150]],
        "labels": [1],
        "frame_idx": 0,
    },
}
predictor.show_prompts(prompts, frame_idx=0)
```
image

**Comment by giswqs** [comment]
Input video

https://github.com/user-attachments/assets/186abbd5-7be0-45dc-ae99-a92c9786d0c6

Point prompts

image

Output video

https://github.com/user-attachments/assets/39ef0a33-3e04-4a1f-bfe1-1cc26bf8bc2a

**Comment by giswqs** [comment]
```python
from samgeo import SamGeo2

predictor = SamGeo2(video=True)
video_path = "landsat_ts"
predictor.set_video(video_path)
prompts = {
    1: {
        "points": [[1582, 933], [1287, 905], [1473, 998]],
        "labels": [1, 1, 1],
        "frame_idx": 0,
    },
}
predictor.show_prompts(prompts, frame_idx=0)
predictor.predict_video(prompts)
predictor.save_video_segments("segments")
```

image

**Pull request merged**
