### PR TITLE
Use headless opencv

### PR DESCRIPTION
**Pull request by jrbourbeau**
Let's see if CI is happy with the changes here 

Closes https://github.com/opengeos/segment-geospatial/issues/273

### CODE REVIEW

**Comment by giswqs** [comment]
Looks great! Thank you for your contribution

**Comment by jrbourbeau** [comment]
Okay, looks like CI is happy here. @giswqs let me know if there's anything else that should be included here (things outside the requirements file were found by just grepping for opencv and libgl)

**Comment by jrbourbeau** [comment]
Whoops, beat me to it. Thanks @giswqs

**Comment by giswqs** [comment]
I will make a new release tonight. Traveling right now

**Pull request merged**
